[tool.poetry]
name = "bot"
authors = ["Interdimensional Walker"]
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
aiohttp = "^3.11"
telethon = "^1.37"
